name: Deploy to prod

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: prod
      image-tag: ${{ github.ref_name }}
    secrets: inherit
